function axPos = combineAxesPositions(axesPos)
%combineAxesPositions Create a Position vector that spans the given Axes
%Positions.
%
%   Inputs:
%   axesPos: Cell array of Position vectors for Axes objects, generated by
%       createAxesPositions
%
%   Outputs:
%   axPos: Position vector that spans the given Axes Positions
%
% Copyright (c) 2026, UMC Utrecht
% Max van Riel, m.h.c.vanriel-3@umcutrecht.nl

minw = min(cellfun(@(p) p(1), axesPos(:)));
minh = min(cellfun(@(p) p(2), axesPos(:)));
maxw = max(cellfun(@(p) p(1)+p(3), axesPos(:)));
maxh = max(cellfun(@(p) p(2)+p(4), axesPos(:)));
axPos = [minw,minh,maxw-minw,maxh-minh];

end
